export type PlanFeature = string | { text: string; excluded: true };

export const PLANS = [
  {
    name: "Starter",
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: "Perfect for trying SiteBotGPT",
    features: [
      "1 chatbot",
      "Up to 10 messages per day",
      "Website training",
      "Chat widget embed",
      { text: "Document training", excluded: true },
      { text: "Lead capture", excluded: true },
      { text: "Analytics", excluded: true },
    ] as PlanFeature[],
    cta: "Start free",
    href: "/login?callbackUrl=/dashboard/pricing",
    popular: false,
    highlight: false,
  },
  {
    name: "Growth",
    monthlyPrice: 49,
    yearlyPrice: 39,
    description: "For growing teams",
    features: [
      "Up to 3 chatbots",
      "Up to 2,000 messages/month",
      "Website training",
      "Document training",
      "Up to 2,000 pages",
      "Manual refresh",
      "Up to 3 team members",
      "Lead capture",
      "Analytics",
      "Export analytics",
    ] as PlanFeature[],
    cta: "Get started free",
    href: "/login?callbackUrl=/dashboard/pricing",
    popular: true,
    highlight: true,
  },
  {
    name: "Scale",
    monthlyPrice: 149,
    yearlyPrice: 119,
    description: "For scaling businesses",
    features: [
      "Up to 10 chatbots",
      "Up to 10,000 messages/month",
      "Website training",
      "Document training",
      "Up to 20,000 pages",
      "Auto refresh (weekly)",
      "Up to 10 team members",
      "Lead capture",
      "Analytics",
      "API access",
      "Webhooks",
      "Priority support",
    ] as PlanFeature[],
    cta: "Get started free",
    href: "/login?callbackUrl=/dashboard/pricing",
    popular: false,
    highlight: false,
  },
  {
    name: "Enterprise",
    monthlyPrice: null,
    yearlyPrice: null,
    description: "Custom for large organizations",
    features: [
      "Unlimited chatbots",
      "Custom message volume",
      "Website training",
      "Document training",
      "Unlimited pages",
      "Auto refresh (daily)",
      "Unlimited team members",
      "Lead capture",
      "Analytics",
      "API & webhooks",
      "Dedicated support",
      "Custom integrations",
    ] as PlanFeature[],
    cta: "Contact us",
    href: "/contact?subject=About%20Enterprise%20Plan",
    popular: false,
    highlight: false,
  },
] as const;
